#ifndef LIBSECP256K1_CONFIG_H
#define LIBSECP256K1_CONFIG_H
#define ENABLE_MODULE_RECOVERY 1
#define ENABLE_MODULE_ECDH 1
#define USE_ECMULT_STATIC_PRECOMPUTATION 1 
#define USE_FIELD_INV_BUILTIN 1 
#define USE_NUM_NONE 1
#define USE_SCALAR_INV_BUILTIN 1
#define USE_FIELD_10X26 1 
#define USE_SCALAR_8X32 1
#define ECMULT_GEN_PREC_BITS 4
#define ECMULT_WINDOW_SIZE 15
#define ECMULT_GEN_PREC_N 64
#define ECMULT_GEN_PREC_G 16
#endif /*LIBSECP256K1_CONFIG_H*/